### ISSUE TITLE
패키지 environment 관리 기능 추가

### ISSUE THREAD

**Issue by choonghyunryu** [bit2r/bitGPT#28]
### Task

- [x] 패키지 environment에 messages 객체 생성
- [x] 패키지 environment에 messages 객체 읽기
- [x] 패키지 environment에 messages 객체 초기화

**Comment by choonghyunryu** [comment]
bitGPT 0.3.6.9001 버전에 추가
