### ISSUE TITLE
README 파일 작성

### ISSUE THREAD

**Issue by choonghyunryu** [bit2r/bitGPT#5]
### Task

- [x] bitGPT 패키지 설치 방법
- [x] openai API key 등록 방법
- [x] Naver 파파고 Client ID/Secret 등록 방법
- [x] Naver 파파고 번역기 사용법
    - translate() 
- [x] Create image with chatGPT 사용법
    - draw_image()
- [x] Create image variation with chatGPT 사용법
    - draw_img_variation()
- [x] chatGPT를 이용한 Speech to Text 사용법
    - transcript_audio()

**Comment by choonghyunryu** [comment]
0.1.0.9000 버전에 반영
